name = "backend"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-03"
kv_namespaces = [ 
  { binding = "newLink", preview_id = "4934ffb1fa9043c99d46093d44da6631", id = "4934ffb1fa9043c99d46093d44da6631" }
]